name: integration

on:
  push:
    branches: [ master ]

jobs:
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-ecr.yml@v2.3.1
    secrets: inherit
  cleanup:
    uses: aeternity/github-actions/.github/workflows/_cleanup-ecr.yml@v2.3.1
    needs: [ publish ]
    secrets: inherit
